# configuration file for git-cliff (0.1.0)

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
"""

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/arttet/git-conventional-commits/issues/${2}))"},
]

commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->:rocket: New Features"},
    { message = "^fix", group = "<!-- 1 -->:bug: Bug Fixes"},
    { message = "^perf", group = "<!-- 2 -->:zap: Performance"},
    { message = "^doc", group = "<!-- 3 -->:notebook: Documentation"},
    { message = "^refactor", group = "<!-- 4 -->:hammer_and_pick: Refactor"},
    { message = "^style", group = "<!-- 5 -->:art: Styling"},
    { message = "^test", group = "<!-- 6 -->:sunny: Testing"},
    { message = "^chore\\(release\\): prepare for", skip = true},
    { message = "^chore", group = "<!-- 7 -->:gear: Miscellaneous Tasks"},
    { body = ".*security", group = "<!-- 8 -->:warning: Security"},
    { message = ".*", group = "Other", skip = true},
]

filter_commits = false
tag_pattern = "v[0-9]+\\.[0-9]+\\.[0-9]+$"
skip_tags = ""
ignore_tags = ""
date_order = false
sort_commits = "oldest"
