name: release

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: git-conventional-commits
  PROJECT_NAME: git-conventional-commits

jobs:
  dist:
    name: Dist ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      CARGO_PROFILE_RELEASE_LTO: true
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            build: x86_64-linux
            os: ubuntu-latest
            cross: false

          - target: x86_64-unknown-linux-musl
            build: x86_64-linux
            os: ubuntu-latest
            cross: false

          - target: aarch64-unknown-linux-musl
            build: aarch64-linux
            os: ubuntu-latest
            cross: true

          - target: x86_64-apple-darwin
            build: x86_64-macos
            os: macos-latest
            cross: false

          - target: aarch64-apple-darwin
            build: aarch64-macos
            os: macos-latest
            cross: false

          - target: x86_64-pc-windows-msvc
            build: x86_64-windows
            os: windows-latest
            cross: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: test
          args: --release --locked --target ${{ matrix.target }} --no-run

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked --target ${{ matrix.target }}

      - name: Strip release binary (linux and macos)
        if: matrix.build == 'x86_64-linux' || matrix.build == 'x86_64-macos'
        run: strip "target/${{ matrix.target }}/release/$APP_NAME"

      - name: Build archive
        shell: bash
        run: |
          mkdir dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "target/${{ matrix.target }}/release/$APP_NAME.exe" "dist/"
          else
            cp "target/${{ matrix.target }}/release/$APP_NAME" "dist/"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bins-${{ matrix.target }}
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [dist]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Generate a changelog
        run: |
            git-cliff --config=cliff.toml -vv --latest --strip header
            echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
            echo "$(cat ${{ env.GIT_CLIFF_OUTPUT }})" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
        env:
          GIT_CLIFF_OUTPUT: CHANGES.md

      - name: Set the release name
        run: echo "RELEASE_NAME=Release ${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check Prerelease
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "PRERELEASE=false" >> $GITHUB_ENV
          else
              echo "PRERELEASE=true" >> $GITHUB_ENV
          fi

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Build archive
        shell: bash
        run: |
          set -ex

          ls -al bins-*
          rm -rf tmp
          mkdir tmp
          mkdir dist

          for dir in bins-* ; do
              platform=${dir#"bins-"}
              unset exe
              if [[ $platform =~ "windows" ]]; then
                  exe=".exe"
              fi
              pkgname=$PROJECT_NAME-$platform
              mkdir tmp/$pkgname

              # cp LICENSE README.md tmp/$pkgname
              mv bins-$platform/$APP_NAME$exe tmp/$pkgname

              chmod +x tmp/$pkgname/$APP_NAME$exe
              if [ "$exe" = "" ]; then
                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
              else
                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
              fi
          done

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: ${{ env.RELEASE_NAME }}
          file: dist/*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          prerelease: ${{ env.PRERELEASE }}
          file_glob: true
          body: ${{ env.RELEASE_BODY }}

  package:
    name: Package
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      packages: write

    env:
      REGISTRY: ghcr.io
      COMMIT_HASH: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set the metadata
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

          REPO_URL=$(cargo metadata --no-deps --format-version=1 | jq --raw-output '. | .packages[0].repository')
          echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV

          DESCRIPTION=$(cargo metadata --no-deps --format-version=1 | jq --raw-output '. | .packages[0].description')
          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "${DESCRIPTION}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Deploy
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_HASH=${{ env.COMMIT_HASH }}
            REPO_URL=${{ env.REPO_URL }}
            DESCRIPTION=${{ env.DESCRIPTION }}
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}

  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    # Allow one concurrent deployment
    concurrency:
      group: 'pages'
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        run: mdbook build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [release, package, gh-pages]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Publish
        run: cargo publish --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
